name = "WignerTransform"
uuid = "9cba2611-9c10-4e73-b35c-8d3655f8d1da"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
